version: "3.6"
services:
  api:
    build: .
    ports:
      - 8000:8000
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: ./api/.env
    volumes:
      - ./:/usr/src/app:ro

# docker-compose up -d
           


